### PR TITLE
Add some router flexibility and control

### PR DESCRIPTION
**Pull request by dlgoodchild**

### CODE REVIEW

**Comment by dlgoodchild** [comment]
I took the naming under advisement and opted for `importControllers`. I believe this change only adds to the usability and potential uptake without adding any risk to existing use. I've updated the jsdocs to explain the limitations of using loadControllers with Koa Router.

**Comment by jeffijoe** [comment]
Thanks! Could you add it to the `API` section in the `README` as well?

**Comment by jeffijoe** [comment]
Turns out I need to migrate this repo from Travis to GitHub Actions before I can merge this. I may need you to close and reopen the PR when that is done, I'll let you know.

**Comment by jeffijoe** [comment]
I have migrated CI to GitHub Actions. Please reopen this PR, and also please use the commit message:

```
feat: add `importControllers` and allow passing router to `loadControllers`
```

That way the CI will automatically release a new minor version when merging. 🙌

**Pull request closed without merging**
